name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Build Project
      run:
        npm install && npm run build --if-present

    - name: List output files
      run: ls

    - name: Deploy
      uses: appleboy/scp-action@master
      env:
        KEY: ${{ secrets.OVH_PRIVATE_KEY }}
        HOST: ${{ secrets.OVH_HOST }}
        USERNAME: ${{ secrets.OVH_USER }}
      with:
        source: "dist"
        target: "test-deploy"
